version: '3'
services:
  mysql:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: linzen_hor
      TZ: Asia/Shanghai
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    command:
      --default-authentication-plugin=mysql_native_password
      --skip-symbolic-links

  redis:
    image: redis:6.2.7
    ports:
      - 6379:6379
    restart: always
    container_name: redis
    hostname: redis
    environment:
        TZ: Asia/Shanghai
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    command: ["redis-server","/etc/redis/redis.conf"]
