spring:
  # 数据源
  datasource:
    url: jdbc:mysql://192.168.0.210:3306/xxl_job_dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: xxl_job_dev
    password: nPLGwNBt32GmyWsL
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: linzen.*.entity;com.xxl.job.admin.core.model
  mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml