spring:
  application:
    name: linzen-boot
  profiles:
    # 指定环境配置 dev(开发环境-默认)、test(测试环境)、preview(预生产)、pro(生产环境)
    active: dev
  servlet:
    multipart: #文件传输配置
      max-file-size: 100MB #单个数据大小限制
      max-request-size: 100MB #请求总数据大小限制
      enabled: true  #是否启用分段上传支持
  mvc:
    hiddenmethod: #隐式方法过滤器
      filter:
        enabled: true #默认开启。开启以支持：PUT,DELETE表单提交方法
  jackson: #序列化和反序列化json框架
    serialization:
      write-dates-as-timestamps: true #是否写入日期时间时间戳格式
    time-zone: GMT+8 #指定日期格式化时区
  main:
    allow-bean-definition-overriding: true #允许同名bean后者覆盖,默认：true
    allow-circular-references: true #允许Bean相互引用,默认：false
config:
  # ===============静态资源目录映射==================
  WebAnnexFilePath: WebAnnexFile
  DataBackupFilePath: DataBackupFile
  TemporaryFilePath: TemporaryFile
  SystemFilePath: SystemFile
  TemplateFilePath: TemplateFile
  EmailFilePath: EmailFile
  DocumentFilePath: DocumentFile
  DocumentPreviewPath: DocumentPreview
  UserAvatarFilePath: UserAvatar
  IMContentFilePath: IMContentFile
  MPMaterialFilePath: MPMaterial
  TemplateCodePath: TemplateCode
  BiVisualPath: BiVisualPath
  # ===============功能格式限制==================
  MPUploadFileType: bmp,png,jpeg,jpg,gif,mp3,wma,wav,amr,mp4
  WeChatUploadFileType: jpg,png,doc,docx,ppt,pptx,xls,xlsx,pdf,txt,rar,zip,csv,amr,mp4

  AllowUploadImageType: jpg,gif,png,bmp,jpeg,tiff,psd,swf,svg,pcx,dxf,wmf,emf,lic,eps,tga #允许上传图片类型
  AllowUploadFileType: jpg,gif,png,bmp,jpeg,doc,docx,ppt,pptx,xls,xlsx,pdf,txt,rar,zip,csv,mp3 #允许上传文件类型
  AllowPreviewFileType: doc,docx,xls,xlsx,ppt,pptx,pdf,jpg,gif,png,bmp,jpeg #允许预览文件类型
  PreviewType: kkfile #文件预览方式 （1.yozo 2.kkfile）默认使用kkfile
  kkFileUrl: http://127.0.0.1:30090/FileServer/ #kkfile文件预览服务地址
  ApiDomain: http://127.0.0.1:30000 #后端域名(文档预览中使用)
  FrontDomain: http://127.0.0.1:3000 #前端域名(文档预览中使用)
  AppDomain: http://127.0.0.1:8080 #app/h5端域名配置(文档预览中使用)

  CodeAreasName: example #代码生成器模块命名


  #===================== unipush =====================
  AppPushUrl: https://8e84eea8-6922-4033-8e86-67ad7442e692.bspapp.com/unipush

  #===================== 多租户 =====================
  MultiTenancy: false #是否开启
  MultiTenancyUrl: http://127.0.0.1:30006/api/tenant/DbName/ #多租户项目地址


  #===================== 系统及错误报告反馈相关 =====================
  SoftName: linzen-boot #项目名
  SoftFullName: LINZEN快速开发平台 #项目全名
  SoftVersion: v0.0.1 #版本号

  RecordLog: true #系统日志启用
  ErrorReport: false #软件错误报告
  ErrorReportTo: surrpot@linzensoft.com #软件错误报告接收者
  IgexinEnabled: true #推送启动

  #===================== APP =====================
  AppVersion: V0.0.1 #APP版本号
  IgexinAppid: ?? #APPID：应用的唯一标识
  IgexinAppkey: ?? #APPKEY：公匙（相当于账号）
  IgexinMastersecret: ?? #Mastersecret：私匙（相当于密码）
  AppUpdateContent: ; #APP更新内容

  #===================== 永中office在线预览配置 =====================
  YozoDomain: //dcsapi.com/ #永中api域名
  YozoDomainKey: ?? #域名key
  YozoCloudDomain: //dmc.yozocloud.cn #云预览
  YozoAppId: ?? #appid
  YozoAppKey: ?? #app秘钥
  YozoEditDomain: //eic.yozocloud.cn #云编辑

  #===================== 系统功能配置 =====================
  EnableLogicDelete: true #是否开启逻辑删除

security:
  # AES加密秘钥
  SecurityKey: EY8WePvjM5GGwQzn
  # 是否开启接口鉴权
  EnablePreAuth: false



# 接口放行地址 与GatewayWhite中的默认URL合并
gateway:
  # 禁止访问接口
  block-url:
  ## 配置示例
  #- /api/message/Notice
  #- /api/permission/Users/*
  # 不验证Token, 放行接口（默认记录日志）
  white-url:
  #  # 配置示例
  #- /api/message/Notice
  #- /api/permission/Users/*
  # 放行接口(不记录日志)
  exclude-url:
  #  # 配置示例
  #- /api/message/Notice
  #- /api/permission/Users/*
  # 入站IP（禁止配置以外的IP访问block-url配置的接口）
  white-ip:
  #- 127.0.0.1
  #- 127.0.0.1

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    #自定义第三方包名日志等级
    # 解除注释后Druid连接池打印SQL语句(在-dev.xml配置打印SQL)
    druid.sql.Statement: debug
#    druid.sql.DataSource: debug
#    druid.sql.Connection: debug
#    druid.sql.ResultSet: debug
log:
  level:
    # 等级 TRACE,DEBUG,INFO,WARN,ERROR(不区分大小写)
    root: info
  path: log/${spring.application.name}