import type { GenItem } from '../types/genItem';
// 表单属性【右面板】
export const formConf = {
  formRef: 'formRef',
  formModel: 'dataForm',
  size: 'default', //large,default,small
  labelPosition: 'right',
  labelWidth: 100,
  labelSuffix: '', // 标题后缀
  formRules: 'rules',
  popupType: 'general',
  generalWidth: '600px',
  fullScreenWidth: '100%',
  drawerWidth: '600px',
  gutter: 15,
  disabled: false,
  span: 24,
  colon: false,
  hasCancelBtn: true,
  cancelButtonText: '取消',
  hasConfirmBtn: true,
  confirmButtonText: '确定',
  hasConfirmAndAddBtn: true,
  hasPrintBtn: false,
  printButtonText: '打印',
  primaryKeyPolicy: 1,
  concurrencyLock: false,
  logicalDelete: false,
  printId: '',
  formStyle: '',
  classNames: [],
  className: [],
  classJson: '',
  funcs: {
    onLoad: '({ formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    beforeSubmit:
      '({ formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    return new Promise((resolve, reject) => {\n        // 在此编写代码\n        \n        // 继续执行\n        resolve()\n    })\n}',
    afterSubmit: '({ formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  },
  idGlobal: 100,
  fields: [],
};

// 基础控件 【左面板】
export const inputComponents: GenItem[] = [
  {
    __config__: {
      projectKey: 'input',
      label: '单行输入',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenInput',
      tagIcon: 'icon-linzen icon-linzen-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: undefined,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showPassword: false,
    readonly: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'textarea',
      label: '多行输入',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenTextarea',
      tagIcon: 'icon-linzen icon-linzen-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: undefined,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请输入',
    autoSize: {
      minRows: 4,
      maxRows: 4,
    },
    clearable: true,
    maxlength: null,
    readonly: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'inputNumber',
      label: '数字输入',
      tipLabel: '',
      showLabel: true,
      labelWidth: undefined,
      tag: 'LinzenInputNumber',
      tagIcon: 'icon-linzen icon-linzen-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: undefined,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请输入',
    min: undefined,
    max: undefined,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: undefined,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'switch',
      label: '开关',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenSwitch',
      tagIcon: 'icon-linzen icon-linzen-generator-switch',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: 0,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    activeTxt: '开',
    inactiveTxt: '关',
    activeValue: 1,
    inactiveValue: 0,
  },
  {
    __config__: {
      projectKey: 'radio',
      label: '单选框组',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenRadio',
      tagIcon: 'icon-linzen icon-linzen-generator-radio',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: undefined,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      templateJson: [],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    options: [
      {
        fullName: '选项一',
        id: '1',
      },
      {
        fullName: '选项二',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    direction: 'horizontal',
    optionType: 'default',
    buttonStyle: 'solid',
    size: 'default',
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'checkbox',
      label: '多选框组',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenCheckbox',
      tagIcon: 'icon-linzen icon-linzen-generator-checkbox',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      templateJson: [],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    options: [
      {
        fullName: '选项一',
        id: '1',
      },
      {
        fullName: '选项二',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    direction: 'horizontal',
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'select',
      label: '下拉选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      templateJson: [],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    options: [
      {
        fullName: '选项一',
        id: '1',
      },
      {
        fullName: '选项二',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
  },
  {
    __config__: {
      projectKey: 'cascader',
      label: '级联选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenCascader',
      tagIcon: 'icon-linzen icon-linzen-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      propsUrl: '',
      propsName: '',
      templateJson: [],
      dictionaryType: '',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    options: [
      {
        id: '1',
        fullName: '选项1',
        children: [
          {
            id: '2',
            fullName: '选项1-1',
          },
        ],
      },
    ],
    props: {
      value: 'id',
      label: 'fullName',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: false,
    multiple: false,
  },
  {
    __config__: {
      projectKey: 'datePicker',
      label: '日期选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenDatePicker',
      tagIcon: 'icon-linzen icon-linzen-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
  },
  {
    __config__: {
      projectKey: 'timePicker',
      label: '时间选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenTimePicker',
      tagIcon: 'icon-linzen icon-linzen-generator-time',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    format: 'HH:mm:ss',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
  },
  {
    __config__: {
      projectKey: 'uploadFile',
      label: '文件上传',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenUploadFile',
      tagIcon: 'icon-linzen icon-linzen-generator-upload',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    accept: '',
    fileSize: 10,
    sizeUnit: 'MB',
    buttonText: '点击上传',
    limit: 9,
    pathType: 'defaultPath',
    isAccount: 0,
    folder: '',
    tipText: '',
  },
  {
    __config__: {
      projectKey: 'uploadImg',
      label: '图片上传',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenUploadImg',
      tagIcon: 'icon-linzen icon-linzen-generator-upload',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    fileSize: 10,
    sizeUnit: 'MB',
    limit: 9,
    pathType: 'defaultPath',
    isAccount: 0,
    folder: '',
    tipText: '',
  },
  {
    __config__: {
      projectKey: 'colorPicker',
      label: '颜色选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenColorPicker',
      tagIcon: 'icon-linzen icon-linzen-generator-color',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    showAlpha: false,
    colorFormat: '',
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'rate',
      label: '评分',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenRate',
      tagIcon: 'icon-linzen icon-linzen-generator-rate',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: 0,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    count: 5,
    allowHalf: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'slider',
      label: '滑块',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenSlider',
      tagIcon: 'icon-linzen icon-linzen-generator-slider',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: 0,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    disabled: false,
    min: 0,
    max: 100,
    step: 1,
  },
  {
    __config__: {
      projectKey: 'editor',
      label: '富文本',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenEditor',
      tagIcon: 'icon-linzen icon-linzen-generator-rich-text',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
    },
    style: { width: '100%' },
    placeholder: '请输入',
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'link',
      label: '链接',
      labelWidth: undefined,
      showLabel: false,
      tag: 'LinzenLink',
      tagIcon: 'icon-linzen icon-linzen-generator-link',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    on: {
      click: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    content: '文本链接',
    href: '',
    target: '_self',
    textStyle: {
      'text-align': 'left',
    },
  },
  {
    __config__: {
      projectKey: 'button',
      label: '按钮',
      labelWidth: undefined,
      showLabel: false,
      tag: 'LinzenButton',
      tagIcon: 'icon-linzen icon-linzen-generator-button',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
      regList: [],
      trigger: 'click',
    },
    on: {
      click: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    align: 'left',
    buttonText: '按钮',
    type: '',
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'text',
      label: '文本',
      labelWidth: undefined,
      showLabel: false,
      tag: 'LinzenText',
      tagIcon: 'icon-linzen icon-linzen-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: undefined,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    textStyle: {
      color: '#000000',
      'text-align': 'left',
      'font-weight': 'normal',
      'font-style': 'normal',
      'text-decoration': 'none',
      'line-height': 32,
      'font-size': 12,
    },
    content: '这是一段文字',
  },
  {
    __config__: {
      projectKey: 'alert',
      label: '提示',
      labelWidth: undefined,
      showLabel: false,
      tag: 'LinzenAlert',
      tagIcon: 'icon-linzen icon-linzen-generator-alert',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    title: '这是一个提示',
    type: 'success',
    showIcon: false,
    closable: true,
    description: '',
    closeText: '',
  },
];

// 高级控件 【左面板】
export const selectComponents: GenItem[] = [
  {
    __config__: {
      projectKey: 'organizeSelect',
      label: '组织选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenOrganizeSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-company',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    multiple: false,
    clearable: true,
    filterable: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'depSelect',
      label: '部门选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenDepSelect',
      tagIcon: 'icon-linzen icon-linzen-tree-department1',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    multiple: false,
    clearable: true,
    filterable: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'posSelect',
      label: '岗位选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenPosSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-jobs',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    multiple: false,
    clearable: true,
    filterable: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'userSelect',
      label: '用户选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenUserSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'roleSelect',
      label: '角色选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenRoleSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-role',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    multiple: false,
    clearable: true,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'groupSelect',
      label: '分组选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenGroupSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-group1',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    multiple: false,
    clearable: true,
    filterable: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'usersSelect',
      label: '用户组件',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenUsersSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    multiple: false,
    clearable: true,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'table',
      label: '设计子表',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: false,
      tagIcon: 'icon-linzen icon-linzen-generator-table',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      tag: 'LinzenInputTable',
      defaultValue: [],
      layout: 'rowFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
      showTitle: true,
      children: [],
      tableName: '',
      complexHeaderList: [],
    },
    disabled: false,
    showSummary: false,
    summaryField: [],
    defaultValue: [],
    columnBtnsList: [
      { value: 'copy', label: '复制', show: true, btnType: 'primary', btnIcon: 'icon-linzen icon-linzen-btn-edit' },
      { value: 'remove', label: '删除', show: true, btnType: 'danger', btnIcon: 'icon-linzen icon-linzen-btn-clearn', showConfirm: true },
    ],
    footerBtnsList: [
      { value: 'add', label: '添加', show: true, btnType: 'primary', btnIcon: 'icon-linzen icon-linzen-btn-add' },
      { value: 'batchRemove', label: '批量删除', show: true, btnType: 'danger', btnIcon: 'icon-linzen icon-linzen-btn-clearn', showConfirm: true },
    ],
  },
  {
    __config__: {
      projectKey: 'treeSelect',
      label: '下拉树形',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenTreeSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-tree',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      templateJson: [],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    options: [
      {
        id: '1',
        fullName: '选项1',
        children: [
          {
            id: '2',
            fullName: '选项1-1',
          },
        ],
      },
    ],
    props: {
      value: 'id',
      label: 'fullName',
      children: 'children',
    },
    placeholder: '请选择',
    multiple: false,
    clearable: true,
    filterable: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'popupTableSelect',
      label: '下拉表格',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      required: false,
      tag: 'LinzenPopupTableSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-popupTableSelect',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    interfaceId: '',
    interfaceName: '',
    templateJson: [],
    hasPage: false,
    pageSize: 20,
    columnOptions: [],
    propsValue: 'id',
    relationField: 'fullName',
    popupType: 'popover',
    popupTitle: '选择数据',
    popupWidth: '800px',
    disabled: false,
    clearable: true,
    multiple: false,
    filterable: true,
  },
  {
    __config__: {
      projectKey: 'autoComplete',
      label: '下拉补全',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      required: false,
      tag: 'LinzenAutoComplete',
      tagIcon: 'icon-linzen icon-linzen-generator-autoComplete',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请输入',
    interfaceId: '',
    interfaceName: '',
    templateJson: [],
    total: 10,
    relationField: 'fullName',
    disabled: false,
    clearable: true,
  },
  {
    __config__: {
      projectKey: 'areaSelect',
      label: '省市区域',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenAreaSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-Provinces',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: false,
    multiple: false,
    level: 2,
  },
  {
    __config__: {
      projectKey: 'relationForm',
      label: '关联表单',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenRelationForm',
      tagIcon: 'icon-linzen icon-linzen-generator-menu',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      transferList: [],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    modelId: '',
    relationField: '',
    hasPage: false,
    pageSize: 20,
    columnOptions: [],
    clearable: true,
    popupType: 'dialog',
    popupTitle: '选择数据',
    popupWidth: '800px',
    filterable: false,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'relationFormAttr',
      label: '关联表单属性',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenRelationFormAttr',
      tagIcon: 'icon-linzen icon-linzen-generator-nature',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    style: { width: '100%' },
    showField: '',
    relationField: '',
    isStorage: 0,
  },
  {
    __config__: {
      projectKey: 'popupSelect',
      label: '弹窗选择',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      required: false,
      tag: 'LinzenPopupSelect',
      tagIcon: 'icon-linzen icon-linzen-generator-popup',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
      transferList: [],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: { width: '100%' },
    placeholder: '请选择',
    interfaceId: '',
    interfaceName: '',
    templateJson: [],
    hasPage: false,
    pageSize: 20,
    columnOptions: [],
    propsValue: 'id',
    relationField: 'fullName',
    popupType: 'dialog',
    popupTitle: '选择数据',
    popupWidth: '800px',
    disabled: false,
    clearable: true,
  },
  {
    __config__: {
      projectKey: 'popupAttr',
      label: '弹窗选择属性',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenPopupAttr',
      tagIcon: 'icon-linzen icon-linzen-generator-popup-attr',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    style: { width: '100%' },
    showField: '',
    relationField: '',
    isStorage: 0,
  },
  {
    __config__: {
      projectKey: 'sign',
      label: '手写签名',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenSign',
      tagIcon: 'icon-linzen icon-linzen-signature',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    clearable: true,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'location',
      label: '定位',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenLocation',
      tagIcon: 'icon-linzen icon-linzen-generator-location',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'change',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    autoLocation: false,
    enableLocationScope: false,
    adjustmentScope: 500,
    enableDesktopLocation: false,
    locationScope: [],
    clearable: true,
    disabled: false,
  },
  {
    __config__: {
      projectKey: 'iframe',
      label: 'Iframe',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenIframe',
      tagIcon: 'icon-linzen icon-linzen-generator-iframe',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc'],
      noShow: false,
    },
    href: '',
    height: 300,
    borderType: 'solid',
    borderColor: '#E2E0E0',
    borderWidth: 1,
  },
];

// 系统控件 【左面板】
export const systemComponents: GenItem[] = [
  {
    __config__: {
      projectKey: 'createUser',
      label: '创建人员',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenOpenData',
      tagIcon: 'icon-linzen icon-linzen-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
    },
    style: { width: '100%' },
    type: 'currUser',
    readonly: true,
    placeholder: '',
  },
  {
    __config__: {
      projectKey: 'createTime',
      label: '创建时间',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenOpenData',
      tagIcon: 'icon-linzen icon-linzen-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
    },
    style: { width: '100%' },
    type: 'currTime',
    readonly: true,
    placeholder: '',
  },
  {
    __config__: {
      projectKey: 'updateUser',
      label: '修改人员',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenInput',
      tagIcon: 'icon-linzen icon-linzen-generator-modifier',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
    },
    style: { width: '100%' },
    readonly: true,
    placeholder: '系统自动生成',
  },
  {
    __config__: {
      projectKey: 'updateTime',
      label: '修改时间',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenInput',
      tagIcon: 'icon-linzen icon-linzen-generator-modifytime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
    },
    style: { width: '100%' },
    readonly: true,
    placeholder: '系统自动生成',
  },
  {
    __config__: {
      projectKey: 'currOrganize',
      label: '所属组织',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenOpenData',
      tagIcon: 'icon-linzen icon-linzen-generator-company',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
    },
    style: { width: '100%' },
    type: 'currOrganize',
    readonly: true,
    showLevel: 'last',
    placeholder: '',
  },
  {
    __config__: {
      projectKey: 'currPosition',
      label: '所属岗位',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenOpenData',
      tagIcon: 'icon-linzen icon-linzen-generator-station',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
    },
    style: { width: '100%' },
    type: 'currPosition',
    readonly: true,
    placeholder: '',
  },
  {
    __config__: {
      projectKey: 'billRule',
      label: '单据组件',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: true,
      tag: 'LinzenInput',
      tagIcon: 'icon-linzen icon-linzen-generator-documents',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      trigger: 'change',
      rule: '',
      ruleName: '',
    },
    style: { width: '100%' },
    readonly: true,
    placeholder: '系统自动生成',
  },
];

// 布局控件 【左面板】
export const layoutComponents: GenItem[] = [
  {
    __config__: {
      projectKey: 'groupTitle',
      label: '分组标题',
      labelWidth: undefined,
      showLabel: false,
      tag: 'LinzenGroupTitle',
      tagIcon: 'icon-linzen icon-linzen-generator-group',
      className: [],
      defaultValue: null,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    helpMessage: '',
    content: '分组标题',
    contentPosition: 'left',
  },
  {
    __config__: {
      projectKey: 'divider',
      label: '分割线',
      labelWidth: undefined,
      showLabel: false,
      tag: 'LinzenDivider',
      tagIcon: 'icon-linzen icon-linzen-generator-divider',
      className: [],
      defaultValue: null,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    content: '我是分割线',
    contentPosition: 'center',
  },
  {
    __config__: {
      projectKey: 'collapse',
      label: '折叠面板',
      labelWidth: undefined,
      showLabel: false,
      tag: 'ACollapse',
      tagIcon: 'icon-linzen icon-linzen-generator-fold',
      className: [],
      layout: 'rowFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
      children: [
        {
          title: '面板1',
          name: '1',
          __config__: {
            projectKey: 'collapseItem',
            children: [],
          },
        },
        {
          title: '面板2',
          name: '2',
          __config__: {
            projectKey: 'collapseItem',
            children: [],
          },
        },
      ],
      active: ['1'],
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    accordion: false,
    ghost: true,
    expandIconPosition: 'right',
  },
  {
    __config__: {
      projectKey: 'tab',
      label: '标签面板',
      labelWidth: undefined,
      showLabel: false,
      tag: 'ATab',
      tagIcon: 'icon-linzen icon-linzen-generator-label',
      className: [],
      layout: 'rowFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
      children: [
        {
          title: 'Tab 1',
          name: '1',
          __config__: {
            projectKey: 'tabItem',
            children: [],
          },
        },
        {
          title: 'Tab 2',
          name: '2',
          __config__: {
            projectKey: 'tabItem',
            children: [],
          },
        },
      ],
      active: '1',
    },
    on: {
      tabClick: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    type: '',
    tabPosition: 'top',
  },
  {
    __config__: {
      projectKey: 'row',
      label: '栅格容器',
      labelWidth: undefined,
      showLabel: false,
      tag: 'ARow',
      tagIcon: 'icon-linzen icon-linzen-generator-layout',
      className: [],
      layout: 'rowFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
    },
    type: 'default',
    justify: 'start',
    align: 'top',
  },
  {
    __config__: {
      projectKey: 'card',
      label: '卡片容器',
      tipLabel: '',
      labelWidth: undefined,
      showLabel: false,
      tag: 'ACard',
      tagIcon: 'icon-linzen icon-linzen-generator-card',
      className: [],
      defaultValue: [],
      layout: 'rowFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
      children: [],
    },
    header: '卡片容器',
    shadow: 'never',
  },
  {
    __config__: {
      projectKey: 'tableGrid',
      label: '表格容器',
      labelWidth: undefined,
      showLabel: false,
      tag: 'Table',
      tagIcon: 'icon-linzen icon-linzen-generator-tableGrid',
      className: [],
      defaultValue: [],
      layout: 'rowFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      noShow: false,
      borderType: 'solid',
      borderColor: '#E2E0E0',
      borderWidth: 1,
      children: [
        {
          __config__: {
            projectKey: 'tableGridTr',
            children: [
              {
                __config__: {
                  projectKey: 'tableGridTd',
                  merged: false,
                  colspan: 1,
                  rowspan: 1,
                  children: [],
                  backgroundColor: '',
                },
              },
            ],
          },
        },
      ],
    },
  },
];
